---
# tasks file for pvwa_hardening

- name: run PVWA hardening
  win_shell: |
    $ErrorActionPreference = "SilentlyContinue"
    $Action = .\PVWA_Hardening.ps1
    $Action | Out-File -FilePath "{{ pvwa_installationautomation_folder }}\pvwa_hardening_result.txt"
    $Result = Get-Content "{{ pvwa_installationautomation_folder }}\pvwa_hardening_result.txt" | ConvertFrom-Json
    if ($Result.isSucceeded -eq 2) {
        exit 1
    } else {
        exit 0
    }
  args:
    chdir: "{{ pvwa_installationautomation_folder }}"

# Validate PVWA Hardening

- name: Get PVWA Service Info
  win_service:
    name: CyberArk Scheduled Tasks
  register: service_info

- name: Set fact on hardening if correct user running the service
  set_fact:
    pvwa_hardened: true
  when: service_info.username == ".\\PVWAReportsUser"